# Generated by Django 6.0.6 on 2026-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.PositiveIntegerField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
